import test from 'node:test';
import assert from 'node:assert/strict';
import {interpret, screening} from '../decision.mjs';
const response=(a,b,c,choice='agenda')=>({answers:{rational:{noul:a},guardian:{noul:b},self:{noul:c},entry:{type:'choice',choice,confidence:.9,probabilities:{}}}});
test('every possible vote combination follows majority; no model can override tally',()=>{for(let i=0;i<8;i++){const votes=[0,1,2].map(bit=>(i>>bit)&1);const r=interpret(response(...votes));assert.equal(r.passed,votes.reduce((a,b)=>a+b)>=2);assert.equal(r.yes+r.no,3);assert.ok(!JSON.stringify(r).includes('noul'));}});
test('an exact probability tie is no',()=>{assert.equal(interpret(response(.5,.51,.5)).passed,false);});
test('missing, invalid and non-finite values never create fake votes',()=>{for(const v of [undefined,null,NaN,Infinity,-1,1.1,'0.8'])assert.throws(()=>interpret(response(v,.8,.8)));assert.throws(()=>interpret({}));});
test('only the agenda entry starts voting; every other category returns its own status',()=>{const cases={emotion:'invalid',multiple:'invalid',fact:'invalid',unclear:'invalid',self_worth:'care',crisis:'care'};for(const [category,status] of Object.entries(cases)){const r=interpret(response(.8,.8,.8,category));assert.equal(r.status,status);assert.equal(r.category,category);assert.equal(r.votes,undefined);assert.ok(r.title&&r.message);}});
test('unknown or missing entry choices never start voting',()=>{for(const choice of [null,'','agendas','ACTIONABLE'])assert.throws(()=>interpret(response(.8,.8,.8,choice)));assert.throws(()=>interpret({answers:{rational:{noul:.8},guardian:{noul:.8},self:{noul:.8}}}));});
test('the entry question is a choice over the seven expected categories',()=>{assert.equal(screening.entry.type,'choice');assert.deepEqual(Object.keys(screening.entry.criteria).sort(),['agenda','crisis','emotion','fact','multiple','self_worth','unclear'].sort());});
